default_platform(:android)

platform :android do
  desc "Build and upload to Play internal track"
  lane :deploy_internal do
    gradle(task: "clean bundleRelease")

    supply(
      track: "internal",
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]
    )
  end
end